### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by remy** [pebble-hacks/color-browser#1]
Because `InverterLayer` isn't supported anymore.

I'm afraid I don't have a solution, only because I hit the same issue in my own pebble app and was hoping it was solved in this code.

**Comment by C-D-Lewis** [comment]
There are two options I can see:
- Use a compatibility `InverterLayer` I have available
- Change the app UI to avoid usage of `InverterLayer`

Which do you think is best here?

**Comment by remy** [comment]
I'd expect to not see `InverterLayer` being used anymore if it's been deprecated. But, I would like to still see _how_ a colour invert would work (via this example). Oh, and I'd like my :cake: too :)

**Comment by C-D-Lewis** [comment]
Then I will remove it. For an example of similar behavior on Basalt, see [here](https://github.com/C-D-Lewis/beam-up/blob/master/src/shim/InverterLayerCompat.h).
